//
// Created by ZhuangTianYi on 15/7/11.
//

#ifndef RECTILINEARSTEINERTREE_COMMON_H
#define RECTILINEARSTEINERTREE_COMMON_H

const int NUM = 100;
const int MAX_RANGE = 1000;

const int SCREEN_SIZE = 500;

#endif //RECTILINEARSTEINERTREE_COMMON_H
